---
name: Spell-check

on:
  pull_request:
    branches:
      - master
      - devel
  push:
    branches:
      - master

jobs:
  spell-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - name: Install dependencies
      run: |
        install.packages("spelling")
      shell: Rscript {0}

    - name: Spell check
      run: |
        Rscript -e 'spelling::spell_check_package()'
        Rscript -e 'spelling::spell_check_test(vignettes = TRUE)'
